from pathlib import Path
from html import escape as e
import json,re
from content import SERVICES, PROJECTS, ARTICLES
from trust import PRIVACY, COOKIES, FAQS
ROOT=Path(__file__).resolve().parent.parent;OUT=ROOT/'dist';ORIGIN='https://helmies-creative-studio.waelhelmi.chatgpt.site'
PAGES=[]
def url(p):return ORIGIN+p
def pill(text,href,style='primary'):return f'<a class="button {style}" href="{href}">{text}<span class="button-bead" aria-hidden="true"></span></a>'
def label(a,b=''):return f'<div class="section-label"><span>{a}</span><span>{b}</span></div>'
def brand():return '<a class="brand" href="/" aria-label="Helmies home"><img src="/assets/helmies-mark.png" width="40" height="40" alt=""><span>helmies<span class="brand-period">.</span></span></a>'
def servicecards(items=SERVICES):return '<div class="service-grid">'+''.join(f'<a class="service-card tilt-card" href="/services/{s["slug"]}/" data-group="{s["group"]}"><div class="card-top"><span class="index">{SERVICES.index(s)+1:02}</span><span class="card-category">{s["group"]}</span></div><h3>{s["name"]}</h3><p>{s["short"]}</p><span class="card-bottom">EXPLORE SERVICE <span class="mini-plus" aria-hidden="true">+</span></span></a>' for s in items)+'</div>'
def articlecards(items=ARTICLES):return '<div class="article-grid">'+''.join(f'<a class="article-card" data-category="{a["category"]}" href="/insights/{a["slug"]}/"><div class="article-meta"><span>{a["category"]}</span><span>{a["read"]}</span></div><h3>{a["title"]}</h3><p>{a["desc"]}</p><span class="card-bottom">READ THE STORY <span class="mini-plus" aria-hidden="true">+</span></span></a>' for a in items)+'</div>'
def cta():return f'<section class="cta section"><div class="cta-light" aria-hidden="true"></div>{label("YOUR NEXT CHAPTER","LET’S MAKE IT REAL")}<div class="cta-content"><p>One conversation can change everything.</p><h2>What if we made<br><span class="gradient-text">something extraordinary?</span></h2><button class="button primary" data-brief>Start a project<span class="button-bead"></span></button><a class="contact-email" href="mailto:info@helmies.fi">info@helmies.fi</a></div></section>'
def faq(items):return '<div class="faq-list">'+''.join(f'<details><summary>{e(q)}<span aria-hidden="true">+</span></summary><p>{e(a)}</p></details>' for q,a in items)+'</div>'
def breadcrumb(parts):return '<nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a>'+''.join(f'<span aria-hidden="true">/</span><a href="{p}">{n}</a>' if p else f'<span aria-hidden="true">/</span><span aria-current="page">{n}</span>' for n,p in parts)+'</nav>'
def introhero(kicker,title,desc,art=None):
 art_html=f'<div class="page-hero-art" data-parallax><img src="/assets/{art}.webp" width="1536" height="1024" alt="" fetchpriority="high"></div>' if art else ''
 return f'<section class="page-hero {"with-art" if art else ""}">{art_html}<div class="page-hero-copy"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{desc}</p></div></section>'
navservices=''.join(f'<a href="/services/{s["slug"]}/"><span>{s["name"]}</span><small>{s["short"]}</small></a>' for s in SERVICES)
header=f'''<aside class="announcement" id="announcement" aria-label="Announcement"><a href="/products/"><span class="badge">COMING NEXT</span> Meet Helmies Studio — our upcoming creative AI workspace <span>Explore Helmies Labs</span></a><button id="dismiss-announcement" aria-label="Dismiss announcement">×</button></aside><a class="skip" href="#main">Skip to content</a><div class="reading-progress" aria-hidden="true"></div><header class="site-header">{brand()}<nav class="desktop-nav" aria-label="Main navigation"><details class="mega"><summary>What we do <span>+</span></summary><div class="mega-panel"><div class="mega-intro"><span class="eyebrow">A WORLD OF POSSIBILITIES</span><h2>Find your<br>next move.</h2><a href="/services/" class="text-link">Explore all services</a></div><div class="mega-links">{navservices}</div></div></details><a href="/studio/">The studio</a><a href="/insights/">Journal</a><a href="/products/">Labs<span class="nav-new">NEW</span></a></nav><div class="header-actions"><button class="search-toggle icon-button" aria-label="Search website"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button><a href="/contact/" class="button small primary">Let’s talk<span class="button-bead"></span></a><button class="menu-toggle icon-button" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 8h18M3 16h18"/></svg></button></div></header><nav id="mobile-nav" aria-label="Mobile navigation" hidden><a href="/services/">What we do</a><a href="/studio/">The studio</a><a href="/approach/">Our approach</a><a href="/insights/">Blog & insights</a><a href="/products/">Helmies Labs</a><a href="/contact/">Let’s talk</a><button data-navigator class="mobile-search">Plan a project</button><button class="search-toggle mobile-search">Search the site</button></nav>'''
footer=f'''<footer class="footer section"><div class="footer-top"><div>{brand()}<p>Human imagination.<br>Intelligent possibilities.</p><span class="eyebrow">FINLAND · WORKING EVERYWHERE</span></div><div class="footer-col"><h3>Explore</h3><a href="/services/">Services</a><button data-navigator>Find my starting point</button><a href="/studio/">The studio</a><a href="/approach/">Our approach</a><a href="/insights/">Blog & insights</a><a href="/products/">Helmies Labs</a></div><div class="footer-col"><h3>Let’s create</h3><a href="/services/ai-solutions/">AI solutions</a><a href="/services/websites/">Websites</a><a href="/services/film-video/">Film & video</a><a href="/services/branding/">Branding</a><a href="/contact/">Start a project</a></div><div class="footer-col"><h3>Stay connected</h3><a href="mailto:info@helmies.fi">info@helmies.fi</a><button data-install>Install Helmies</button><button id="motion-toggle" aria-pressed="false">Motion: on</button><button id="tilt-toggle" aria-pressed="false">Enable device tilt</button></div></div><div class="footer-bottom"><span>© <span id="year">2026</span> HELMIES OY</span><span>DESIGNED TO GO BEYOND.</span><div><a href="/privacy/">Privacy & GDPR</a><a href="/cookies/">Cookies & preferences</a><a href="/faq/">FAQ</a><a href="/llms.txt">AI readers</a><a href="#top">Back to top</a></div></div></footer>'''
brief=(ROOT/'src/brief.html').read_text().replace('class="button orange"','class="button primary"').replace('class="button light"','class="button primary"')
options=''.join(f'<label><input type="checkbox" name="services" value="{e(s["name"],quote=True)}"><span>{s["name"]}</span></label>' for s in SERVICES)+'<label><input type="checkbox" name="services" value="Help me find the right direction"><span>Help me find the right direction</span></label>'
brief=re.sub(r'<div class="brief-options">.*?</div>',f'<div class="brief-options">{options}</div>',brief)
navigator=(ROOT/'src/navigator.html').read_text()
search='''<dialog id="search-dialog" aria-labelledby="search-title"><div class="dialog-top"><h2 id="search-title">Find your next possibility.</h2><button class="close-dialog" data-close aria-label="Close search">×</button></div><label class="search-label" for="site-search">Search services, products, and insights</label><input id="site-search" type="search" placeholder="Try automation, film, branding…" autocomplete="off"><div id="search-results" aria-live="polite"></div></dialog><dialog id="install-dialog" aria-labelledby="install-title"><div class="dialog-top"><h2 id="install-title">Keep Helmies close.</h2><button class="close-dialog" data-close aria-label="Close installation help">×</button></div><img class="install-logo" src="/assets/icon-transparent-192.png" width="96" height="96" alt="Helmies"><p>Add Helmies to your home screen for a standalone experience. You can separately enable offline pages in <a href="/cookies/">Cookies & preferences</a>.</p><p id="install-help">In your browser menu, look for “Install app” or “Add to Home Screen”. On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen.</p><button id="install-now" class="button primary" hidden>Install app</button><p class="muted small-copy">Availability depends on your browser. Offline availability requires your opt-in and depends on the pages saved on your device.</p></dialog><div id="toast" class="toast" role="status" hidden></div>'''
def write_page(path,title,desc,body,kind='WebPage',extra=None,crumbs=None):
 PAGES.append(dict(path=path,title=title,description=desc))
 schemas=[{'@context':'https://schema.org','@type':kind,'@id':url(path)+'#page','url':url(path),'name':title,'description':desc,'isPartOf':{'@id':ORIGIN+'/#website'}}]
 if path=='/':schemas.append({'@context':'https://schema.org','@type':'WebSite','@id':ORIGIN+'/#website','name':'Helmies','url':ORIGIN})
 if extra:schemas.append({'@context':'https://schema.org',**extra})
 if crumbs:schemas.append({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':i+1,'name':n,'item':url(p)} for i,(n,p) in enumerate([('Home','/')]+crumbs)]})
 canonical=url(path)
 scene_script='<link rel="stylesheet" href="/founder.css?v=9"><script src="/founder.js?v=9" defer></script><script src="/scene.js?v=7" defer></script>' if path=='/' else ''
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="helmies-page" content="v2"><title>{e(title)} | Helmies</title><meta name="description" content="{e(desc,quote=True)}"><link rel="canonical" href="{canonical}"><meta name="theme-color" content="#0b081a"><meta property="og:type" content="website"><meta property="og:title" content="{e(title,quote=True)} | Helmies"><meta property="og:description" content="{e(desc,quote=True)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="https://www.helmies.fi/assets/images/og-image.webp"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="https://www.helmies.fi/assets/images/og-image.webp"><link rel="icon" href="/assets/icon-transparent-192.png" type="image/png"><link rel="apple-touch-icon" href="/assets/icon-transparent-180.png"><link rel="manifest" href="/manifest.webmanifest"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/cinema.css?v=7"><link rel="stylesheet" href="/content.css?v=10"><script src="/app.js?v=10" defer></script><script src="/content.js?v=10" defer></script><script src="/navigator.js" defer></script>{scene_script}<script type="application/ld+json">{json.dumps(schemas,ensure_ascii=False).replace('</','<\\/')}</script></head><body id="top" data-page="{path}">{header}<main id="main">{body}</main>{footer}{brief}{search}{navigator}</body></html>'''
 target=OUT/path.strip('/')/'index.html' if path!='/' else OUT/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(html)
# HOME
home=(ROOT/'src/experience.html').read_text()+(ROOT/'src/home-quality.html').read_text().replace('{{FOUNDER}}',(ROOT/'src/founder.html').read_text()).replace('{{INTELLIGENCE}}',(ROOT/'src/intelligence.html').read_text()).replace('{{ARTICLES}}',articlecards(ARTICLES[:3]))
write_page('/','Creative technology, AI & design studio', 'Helmies is a Finland-based studio for AI, automation, apps, websites, films, music, branding and advertising. Human imagination. Intelligent possibilities.',home,extra={'@type':'ProfessionalService','@id':ORIGIN+'/#studio','name':'Helmies Oy','url':ORIGIN,'email':'info@helmies.fi','address':{'@type':'PostalAddress','addressCountry':'FI'},'founder':{'@type':'Person','name':'Wael Helmi'},'sameAs':['https://www.behance.net/waelosama'],'hasOfferCatalog':{'@type':'OfferCatalog','name':'Services','itemListElement':[{'@type':'Offer','itemOffered':{'@type':'Service','name':s['name'],'url':url('/services/'+s['slug']+'/')}} for s in SERVICES]}})
# SERVICES INDEX
body=breadcrumb([('Services',None)])+introhero('WHAT WE DO','A whole universe<br>of <span class="gradient-text">possibility.</span>','Ten connected disciplines. From the workflow that saves your team another manual handoff to the brand, website, or film that introduces your next chapter.','logo-3d')
body+='<section class="section services-directory">'+label('FIND YOUR NEXT MOVE','EXPLORE BY DISCIPLINE')+'<div class="filter-bar" role="group" aria-label="Filter services">'+''.join(f'<button id="{g.lower()}" data-service-filter="{g}" aria-pressed="{str(g=="All").lower()}">{g}</button>' for g in ['All','Intelligence','Digital','Creative','Growth'])+'</div><p class="filter-status" aria-live="polite">10 services</p>'+servicecards()+'</section>'
body+='<section class="section combination">'+label('BETTER TOGETHER','ONE IDEA. MULTIPLE DIMENSIONS.')+'<h2>Connect the dots.</h2><div class="three-grid"><article><span>FOR A NEW BUSINESS</span><h3>From identity to launch.</h3><p>Brand strategy, a distinctive website, and the campaign that introduces you to the world.</p></article><article><span>FOR A GROWING TEAM</span><h3>From busy to better.</h3><p>An internal app, connected workflows, and an AI assistant that makes knowledge easier to use.</p></article><article><span>FOR A BIG STORY</span><h3>From idea to emotion.</h3><p>A visual world, a cinematic film, and a sound that brings the whole experience together.</p></article></div><button class="button primary" data-brief>Find my combination<span class="button-bead"></span></button></section>'+cta()
write_page('/services/','AI, digital & creative services', 'Explore ten Helmies services: AI, automation, apps, websites, branding, design, film, music, advertising, and interactive 3D.',body,crumbs=[('Services','/services/')])
# SERVICE DETAIL PAGES
for i,s in enumerate(SERVICES):
 parts=s['lead'].split('\n');title=parts[0]+'<br><span class="gradient-text">'+parts[1]+'</span>'
 body=breadcrumb([('Services','/services/'),(s['name'],None)])+introhero(f'{i+1:02} / {s["name"].upper()}',title,s['desc'],'ribbons' if s['group'] in ['Creative','Growth'] else 'logo-3d')
 body+=f'<section class="section service-overview"><div><p class="eyebrow">{s["group"].upper()} / HELMIES</p><h2>{s["short"]}</h2><p class="body-large">{s["intro"]}</p><button class="button primary" data-service="{e(s["name"],quote=True)}">Let’s talk about {"your project" if len(s["name"])>18 else s["name"].lower()}<span class="button-bead"></span></button></div><aside class="deliverables"><span class="eyebrow">WHAT WE CAN CREATE</span><ul>'+''.join(f'<li><span>0{j+1}</span>{o}</li>' for j,o in enumerate(s['outputs']))+'</ul></aside></section>'
 body+='<section class="section use-cases">'+label('BUILT AROUND YOUR WORLD','POSSIBLE STARTING POINTS')+'<h2>What could this<br><span class="soft-text">make possible?</span></h2><div class="three-grid">'+''.join(f'<article class="reveal"><span>0{j+1}</span><h3>{h}</h3><p>{p}</p></article>' for j,(h,p) in enumerate(s['uses']))+'</div></section>'
 body+='<section class="section detail-process"><div><p class="eyebrow">HOW WE GET THERE</p><h2>A clear path<br>to <span class="gradient-text">what’s next.</span></h2><a class="text-link" href="/approach/">Explore our approach</a></div><ol>'+''.join(f'<li><span>0{j+1}</span><p>{p}</p></li>' for j,p in enumerate(s['process']))+'</ol></section>'
 body+='<section class="section faq-section"><div><p class="eyebrow">A FEW GOOD QUESTIONS</p><h2>Before<br>we begin.</h2></div>'+faq(s['faq'])+'</section>'
 body+='<section class="section content-readiness">'+label('MAKE THE FIRST CONVERSATION COUNT','YOUR STARTING POINT')+'<div class="three-grid"><article><h3>Bring the context.</h3><p>Tell us who the work is for, what is difficult today, and what a useful change would look like. Share relevant existing material so we can understand the starting point.</p></article><article><h3>Choose the first outcome.</h3><p>We can prioritize '+s['outputs'][0].lower()+' or another focused deliverable, then agree what belongs in this stage and what can follow.</p></article><article><h3>Plan for real use.</h3><p>Who will approve the work, keep it current, and use the handover? Clarifying those roles helps the result become part of your everyday business.</p></article></div></section>'
 reading=[a for a in ARTICLES if a['related']==s['slug']]
 if reading:body+='<section class="section">'+label('BEFORE YOU BEGIN','FROM THE JOURNAL')+articlecards(reading[:3])+'</section>'
 related=[other for other in SERVICES if other['slug']!=s['slug'] and other['group']==s['group']][:3]
 if len(related)<2:related=[SERVICES[0],SERVICES[3],SERVICES[4]][:3]
 body+='<section class="section">'+label('KEEP EXPLORING','CONNECTED DISCIPLINES')+servicecards(related)+'</section>'+cta()
 write_page('/services/'+s['slug']+'/',s['name']+' services',s['desc'],body,extra={'@type':'Service','name':s['name'],'serviceType':s['name'],'description':s['desc'],'provider':{'@id':ORIGIN+'/#studio'},'url':url('/services/'+s['slug']+'/'),'areaServed':'Worldwide'},crumbs=[('Services','/services/'),(s['name'],'/services/'+s['slug']+'/')])
# Retire the generated portfolio routes; retain project data and assets in source.
for retired in [OUT/'work/index.html', *(OUT/'work'/p['slug']/'index.html' for p in PROJECTS)]:
 retired.unlink(missing_ok=True)
# STUDIO
body=breadcrumb([('The studio',None)])+introhero('INDEPENDENT BY DESIGN','A curious mind.<br><span class="gradient-text">An open universe.</span>','Helmies connects design, development, and storytelling. We’re here for the ideas that don’t fit neatly into one discipline.','logo-3d')
body+='<section class="section studio-story"><div><p class="eyebrow">FOUNDED BY WAEL HELMI</p><h2>Design meets code.<br>Then things<br><span class="gradient-text">get interesting.</span></h2></div><div><p class="body-large">Helmies grew from a practice that moves between visual identity, digital products, automation, and creative production.</p><p>That range is useful. It means a visual idea can be considered alongside the system that supports it. A business problem can lead to an app, an automation, a clearer message—or a combination of all three.</p><p>Founded by Wael Helmi and based in Finland, the studio works remotely with clients and collaborators. Conversations can happen in English, Finnish, or Arabic.</p><div class="founder-line"><img src="/assets/helmies-mark.png" width="60" height="60" alt="Helmies logo"><div><strong>Wael Helmi</strong><span>FOUNDER · DESIGNER · DEVELOPER</span></div></div></div></section><section class="section values">'+label('WHAT GUIDES THE WORK','A FEW THINGS WE BELIEVE')+'<div class="three-grid"><article><span>01 / CURIOSITY</span><h3>Ask a better question.</h3><p>The first request is sometimes the start of the brief. We look for the underlying problem before choosing the medium or tool.</p></article><article><span>02 / CRAFT</span><h3>Care about the details.</h3><p>The rhythm of an edit, the clarity of a form, the recovery path in an automation. Small decisions shape the whole experience.</p></article><article><span>03 / INTENTION</span><h3>Use technology with purpose.</h3><p>AI and automation are useful when they serve a real need. We choose an approach around the project, not the trend.</p></article></div></section>'+cta()
body=body.replace(cta(),'<section class="section content-readiness">'+label('A FOUNDER-LED PRACTICE','ONE CONNECTED CONVERSATION')+'<div class="three-grid"><article><h3>Direct creative dialogue.</h3><p>Discuss the problem with the person connecting the design and technical decisions. Clear conversations help the idea stay coherent as it moves between disciplines.</p></article><article><h3>A team around the brief.</h3><p>Different projects need different skills. The scope defines responsibilities, collaborators where needed, review stages, and what you will receive.</p></article><article><h3>Knowledge that stays useful.</h3><p>Handover is part of the work. We agree on practical files, guidance, and ownership so your next step does not depend on remembering a presentation.</p></article></div><a class="text-link" href="/faq/">Questions about working together</a></section>'+cta())
write_page('/studio/','About the studio & Wael Helmi','Meet Helmies, a Finland-based creative technology studio founded by designer and developer Wael Helmi.',body,extra={'@type':'AboutPage','name':'About Helmies','about':{'@id':ORIGIN+'/#studio'}},crumbs=[('The studio','/studio/')])
# APPROACH
stages=[('Discover','Start with the right question.','We listen to the ambition, look at the context, and define the problem worth solving. We agree on the audience, the scope, and what a useful result should look like.',['Discovery conversation','Scope & priorities','Success criteria']),('Imagine','Make the direction tangible.','A prototype, a moodboard, a storyboard, or a proof of concept. We create something concrete enough to react to before the project moves into full production.',['Creative direction','Early prototype','Feedback & alignment']),('Create','Build with the details in mind.','Design and production move in reviewable stages. We share progress, test the important parts, and refine the work around the agreed purpose.',['Design & production','Milestone reviews','Testing & refinement']),('Evolve','Give the launch a future.','We prepare the agreed deliverables, clarify how they should be used, and plan the next chapter. Maintenance and further development can be scoped around the needs of the project.',['Launch preparation','Handover & guidance','Next-step planning'])]
body=breadcrumb([('Our approach',None)])+introhero('HOW WE WORK','Room for wonder.<br><span class="gradient-text">A plan to get there.</span>','A collaborative process that turns an ambitious idea into something you can see, use, and share.')+'<section class="section approach-stages">'+''.join(f'<article class="stage reveal"><div class="stage-number">0{i+1}</div><div><p class="eyebrow">{name.upper()}</p><h2>{head}</h2><p>{desc}</p><ul class="tags">'+''.join(f'<li>{tag}</li>' for tag in tags)+'</ul></div></article>' for i,(name,head,desc,tags) in enumerate(stages))+'</section><section class="section faq-section"><div><p class="eyebrow">WORKING TOGETHER</p><h2>Clear from<br>the beginning.</h2></div>'+faq([('How do we start?','Share a short brief or email us. We’ll discuss the idea and shape an appropriate next step.'),('How are budget and timing decided?','We review the scope, complexity, content, and dependencies before agreeing on a proposal. No fixed timeline fits every type of work.'),('Can you collaborate with our team?','Yes. We can take on a defined part of a project or bring several disciplines together, with responsibilities agreed in advance.'),('What happens after delivery?','We agree on handover, documentation, and any support needs as part of the scope. Ongoing maintenance and development can be planned separately.')])+'</section>'+cta()
write_page('/approach/','Our creative & development process','Discover how Helmies works: discovery, creative direction, production, launch and the next stage of your project.',body,crumbs=[('Our approach','/approach/')])
# INSIGHTS
featured=ARTICLES[0]
body=breadcrumb([('Blog & insights',None)])+introhero('THE HELMIES JOURNAL','Good questions.<br><span class="gradient-text">Useful perspectives.</span>','Practical guides to building a brand, launching a digital product, connecting your work, and telling a stronger story.')
body+='<section class="section insights-directory"><div class="journal-feature"><div><p class="eyebrow">START HERE / DIGITAL</p><h2>'+featured['title']+'</h2></div><div><p>'+featured['desc']+'</p>'+pill('Read the guide','/insights/'+featured['slug']+'/','primary')+'</div></div><div class="journal-topic" role="group" aria-label="Filter articles by topic">'+''.join(f'<button data-article-filter="{c}" aria-pressed="{str(c=="All").lower()}">{c}</button>' for c in ['All','Intelligence','Digital','Design','Film'])+'</div><p id="journal-count" class="journal-count" role="status">'+str(len(ARTICLES))+' articles</p>'+articlecards()+'</section>'+cta()
write_page('/insights/','Blog & insights on design, AI and digital products','Original Helmies guides on websites, app planning, branding, AI, automation and filmmaking.',body,crumbs=[('Blog & insights','/insights/')])
for a in ARTICLES:
 body=breadcrumb([('Insights','/insights/'),(a['category'],None)])+f'<article class="editorial"><header><p class="eyebrow">{a["category"].upper()} / {a["read"]}</p><h1>{a["title"]}</h1><p class="article-deck">{a["intro"]}</p><div class="byline">HELMIES JOURNAL · <time datetime="2026-10-05">5 OCTOBER 2026</time></div></header><div class="article-layout"><aside><span class="eyebrow">IN THIS STORY</span><nav aria-label="Article contents">'+''.join(f'<a href="#part-{i}">{h}</a>' for i,(h,p) in enumerate(a['sections']))+'</nav></aside><div class="article-body">'+''.join(f'<section id="part-{i}"><h2>{h}</h2>'+''.join('<p>'+e(paragraph)+'</p>' for paragraph in p.split('\n\n'))+'</section>' for i,(h,p) in enumerate(a['sections']))+f'<div class="article-end"><p>Have a project in mind?</p>{pill("Explore the related service","/services/"+a["related"]+"/","primary")}</div></div></div></article><section class="section">'+label('KEEP READING','MORE STUDIO NOTES')+articlecards(sorted([b for b in ARTICLES if b!=a],key=lambda b:b['category']!=a['category'])[:3])+'</section>'
 write_page('/insights/'+a['slug']+'/',a['title'],a['desc'],body,kind='Article',extra={'@type':'Article','headline':a['title'],'datePublished':'2026-10-05','dateModified':'2026-10-05','description':a['desc'],'author':{'@type':'Organization','name':'Helmies'},'publisher':{'@id':ORIGIN+'/#studio'},'mainEntityOfPage':url('/insights/'+a['slug']+'/')},crumbs=[('Insights','/insights/'),(a['title'],'/insights/'+a['slug']+'/')])
# CONTACT
body=breadcrumb([('Contact',None)])+introhero('LET’S START SOMETHING','Big ambition.<br><span class="gradient-text">Small first step.</span>','Tell us what you’re thinking. A clear brief is welcome. A beautifully messy idea is welcome too.','ribbons')+'<section class="section contact-layout"><div class="contact-brief"><span class="eyebrow">YOUR NEXT CHAPTER</span><h2>What are you<br>imagining?</h2><p>Choose your services, share a little context, and prepare a brief to send to Helmies. It takes a few minutes.</p><button class="button primary" data-brief>Build my project brief<span class="button-bead"></span></button><span class="small-copy muted">You review and send the email yourself.</span></div><div class="contact-details"><span class="eyebrow">PREFER A CONVERSATION?</span><a class="big-email" href="mailto:info@helmies.fi">info@helmies.fi</a><dl><div><dt>BASED IN</dt><dd>Finland · Working remotely</dd></div><div><dt>LANGUAGES</dt><dd>English · Finnish · Arabic</dd></div></dl></div></section><section class="section faq-section"><div><p class="eyebrow">BEFORE YOU SAY HELLO</p><h2>A little<br>more clarity.</h2></div>'+faq([('Do I need to know exactly what I need?','No. Share the problem, idea, or ambition and we can help identify the right combination of services.'),('Can I book just one service?','Yes. A focused design task, an automation, or a film concept can be scoped independently.'),('Will the brief form send my details automatically?','No. It prepares an email that you review and send from your own email app. You can also copy the brief.'),('Can I contact you outside Finland?','Yes. The studio works remotely and can plan communication around the project and your timezone.')])+'</section>'
write_page('/contact/','Start a project with Helmies','Discuss your next AI, automation, digital or creative project with Helmies. Email info@helmies.fi or prepare a project brief.',body,kind='ContactPage',crumbs=[('Contact','/contact/')])
# UPCOMING PRODUCTS
studio_preview='''<div class="product-preview studio-preview"><div class="preview-chrome"><div class="window-dots" aria-hidden="true"><i></i><i></i><i></i></div><span>HELMIES STUDIO</span><span class="preview-status">CONCEPT PREVIEW</span></div><div class="preview-body"><aside><span class="preview-logo">h.</span><span class="active">Create</span><span>Projects</span><span>Brand Kits</span><span>Assets</span></aside><div class="preview-main"><span class="eyebrow">WHAT WILL YOU CREATE?</span><h3>One idea.<br>So many possibilities.</h3><div class="preview-tabs" role="group" aria-label="Explore Studio workflow concepts"><button data-studio-mode="film" aria-pressed="true">Film</button><button data-studio-mode="image" aria-pressed="false">Image</button><button data-studio-mode="music" aria-pressed="false">Music</button><button data-studio-mode="campaign" aria-pressed="false">Campaign</button></div><div class="preview-prompt"><span class="prompt-symbol" aria-hidden="true">✳</span><p id="studio-prompt">Turn my idea into a cinematic short film.</p></div><div class="preview-flow" aria-live="polite"><span id="studio-step-1">Shape the story</span><span id="studio-step-2">Plan the shots</span><span id="studio-step-3">Create & refine</span></div><div class="preview-visual"><img src="/assets/ribbons.webp" width="1536" height="1024" alt="Illustrative creative direction in lavender glass"><span>YOUR CREATIVE WORLD, CONNECTED</span></div></div></div><div class="preview-footnote">ILLUSTRATIVE WORKFLOW · NOT A LIVE GENERATION TOOL</div></div>'''
def productcards():return '<div class="product-cards"><a class="product-card studio-product" href="/products/helmies-studio/"><div class="product-card-art"><img src="/assets/ribbons.webp" width="1536" height="1024" loading="lazy" alt="Iridescent creative world for Helmies Studio"><span class="status-pill">IN DEVELOPMENT</span><span class="product-mark">Studio.</span></div><div class="product-card-copy"><span class="eyebrow">THE CREATIVE AI WORKSPACE</span><h3>Helmies Studio</h3><p>One idea. A connected production team. Explore the vision for conversational image, video, music, and campaign creation.</p><span class="card-bottom">EXPLORE THE VISION <span class="mini-plus" aria-hidden="true">+</span></span></div></a></div>'
body=breadcrumb([('Helmies Labs',None)])+introhero('HELMIES LABS / UPCOMING PRODUCTS','The things<br>we <span class="gradient-text">wish existed.</span>','We build for our clients. We also build for the possibilities we see ahead. Meet the next chapter of the Helmies ecosystem.','logo-3d')+'<section class="section">'+label('FROM THE STUDIO. FOR YOUR WORLD.','PRODUCTS IN THE MAKING')+productcards()+'</section><section class="section product-principles">'+label('ONE CONNECTED IDEA','LESS FRICTION. MORE POSSIBILITY.')+'<div class="split-intro"><h2>Our curiosity.<br><span class="gradient-text">Your next possibility.</span></h2><p>Each product starts with a question worth exploring. These previews share the direction of the work, with product details and availability announced as development progresses.</p></div></section>'
write_page('/products/','Helmies Labs — upcoming SaaS products','Explore Helmies Studio, an upcoming conversational AI creative workspace from Helmies Labs.',body,crumbs=[('Helmies Labs','/products/')])
body=breadcrumb([('Helmies Labs','/products/'),('Helmies Studio',None)])+introhero('HELMIES STUDIO / IN DEVELOPMENT','One tool.<br>One prompt.<br><span class="gradient-text">A world of creation.</span>','An upcoming creative AI workspace built around a simple idea: describe what you want to make, then shape it through conversation.','ribbons')+'<section class="section product-demo-section">'+studio_preview+'<p class="preview-note">A visual concept of the planned workflow. Interfaces and capabilities may evolve before release.</p></section><section class="section product-story"><div><p class="eyebrow">YOUR CREATIVE PRODUCTION TEAM</p><h2>Start with the outcome.<br><span class="gradient-text">Keep the conversation.</span></h2></div><div><p class="body-large">The vision for Helmies Studio brings image, video, music, voice, and creative workflows into one connected workspace.</p><p>A central creative assistant helps shape the plan and coordinates specialized tasks. You guide the direction, review the work, and refine it through conversation. Dedicated tools remain part of the vision for people who want more hands-on control.</p></div></section><section class="section use-cases">'+label('THE PLANNED CREATIVE UNIVERSE','ONE WORKSPACE. CONNECTED DISCIPLINES.')+'<div class="three-grid"><article><span>01 / VISUALS</span><h3>Imagine the image.</h3><p>Explore concepts, visual references, and brand-aligned images within a shared creative project.</p></article><article><span>02 / FILM</span><h3>Direct the story.</h3><p>Bring story planning, scenes, shots, and video production into a connected creative workflow.</p></article><article><span>03 / SOUND</span><h3>Find the feeling.</h3><p>Develop music, audio, and voice alongside the visual direction of your project.</p></article><article><span>04 / CAMPAIGNS</span><h3>Build the whole idea.</h3><p>Connect product ads, social content, and campaign assets around the outcome you want to create.</p></article><article><span>05 / BRAND MEMORY</span><h3>Keep it recognizably you.</h3><p>The planned workspace includes Brand Kits, reusable assets, and project context to support continuity.</p></article><article><span>06 / CONTROL</span><h3>Create your way.</h3><p>Move between a guided conversation and dedicated creative tools as the task requires.</p></article></div></section><section class="section product-interest"><span class="status-pill">IN DEVELOPMENT</span><h2>Be part of<br><span class="gradient-text">what comes next.</span></h2><p>Interested in the creative workspace? Email us about early access. Launch timing, pricing, and availability will be announced separately.</p>'+pill('Ask about early access','mailto:info@helmies.fi?subject=Helmies%20Studio%20early%20access','primary')+'<span class="small-copy muted">Opens your email app. No automatic subscription.</span></section>'
write_page('/products/helmies-studio/','Helmies Studio — upcoming creative AI workspace','Discover the vision for Helmies Studio: one conversational workspace for image, video, music, voice, brand assets, and creative workflows.',body,crumbs=[('Helmies Labs','/products/'),('Helmies Studio','/products/helmies-studio/')])
# PRIVACY / OFFLINE
for path,title,description,content in [('/privacy/','Privacy & GDPR','How Helmies handles website visits, enquiries, browser data, and personal-data requests.',PRIVACY),('/cookies/','Cookies & device preferences','Understand and manage Helmies browser preferences and optional offline pages.',COOKIES)]:
 body=breadcrumb([(title,None)])+'<article class="legal section">'+content+'</article>'
 write_page(path,title,description,body,crumbs=[(title,path)])
body=breadcrumb([('Frequently asked questions',None)])+introhero('WORKING WITH HELMIES','A little clarity.<br><span class="gradient-text">Before we begin.</span>','Scope, budgets, content, collaboration, handover, and the first conversation. Here is how to prepare for a useful start.')+'<section class="section faq-section"><div><p class="eyebrow">PROJECT QUESTIONS</p><h2>From first idea<br>to handover.</h2></div>'+faq(FAQS)+'</section>'+cta()
write_page('/faq/','Frequently asked questions','Answers about starting a Helmies project, budgets, revisions, content, handover and support.',body,crumbs=[('FAQ','/faq/')])
write_page('/offline/','You are offline','Reconnect to explore more of Helmies.',introhero('A MOMENT OFFLINE','The possibilities<br><span class="gradient-text">will wait.</span>','This page hasn’t been saved on your device yet. Reconnect to keep exploring, or return to a page you’ve already visited.')+'<section class="section offline-links">'+pill('Return home','/','primary')+pill('Explore services','/services/','ghost')+'</section>')
# Actual 404 document, separate from routable pages
html=(OUT/'offline/index.html').read_text().replace('A MOMENT OFFLINE','404 / A DIFFERENT DIRECTION').replace('The possibilities<br><span class="gradient-text">will wait.</span>','This path is<br><span class="gradient-text">unexplored.</span>').replace('This page hasn’t been saved on your device yet. Reconnect to keep exploring, or return to a page you’ve already visited.','We couldn’t find that page. Explore the services or return home to choose a new direction.').replace('<title>You are offline | Helmies</title>','<title>Page not found | Helmies</title>').replace('<link rel="canonical" href="'+url('/offline/')+'">','<meta name="robots" content="noindex">')
(OUT/'404.html').write_text(html)
(OUT/'search-index.json').write_text(json.dumps([p for p in PAGES if p['path']!='/offline/'],ensure_ascii=False))
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+url(p['path'])+'</loc></url>' for p in PAGES if p['path']!='/offline/')+'</urlset>')
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /offline/\nSitemap: '+ORIGIN+'/sitemap.xml\n')
(OUT/'llms.txt').write_text('# Helmies Oy\n\n> Independent creative technology studio based in Finland, founded by Wael Helmi. Working remotely in English, Finnish, and Arabic.\n\nContact: info@helmies.fi\n\n## Services\n'+''.join(f'- [{s["name"]}]({url("/services/"+s["slug"]+"/")}): {s["desc"]}\n' for s in SERVICES)+'\n## Site pages\n'+''.join(f'- [{p["title"]}]({url(p["path"])}): {p["description"]}\n' for p in PAGES if not p['path'].startswith('/services/') and p['path']!='/offline/')+'\n## Important context\nPricing and timelines are agreed per project. The brief builder only prepares an email; visitors review and send it themselves. The website provides structured service pages and this text summary for AI readers.\n')
manifest={'id':'/','name':'Helmies — Creative Technology Studio','short_name':'Helmies','description':'Explore AI, digital experiences, and creative possibilities.','lang':'en','start_url':'/','scope':'/','display':'standalone','background_color':'#0b081a','theme_color':'#0b081a','icons':[{'src':f'/assets/icon-transparent-{s}.png','sizes':f'{s}x{s}','type':'image/png','purpose':'any'} for s in [192,512]],'shortcuts':[{'name':'Explore services','url':'/services/'},{'name':'Start a project','url':'/contact/'}]}
(OUT/'manifest.webmanifest').write_text(json.dumps(manifest,indent=2))
print(f'Generated {len(PAGES)} pages + 404, search index, sitemap, AI summary and PWA manifest.')
