"""Original editorial guides for the Helmies journal."""
NEW_ARTICLES = [
 dict(slug='website-brief-that-gets-results',category='Digital',title='How to write a website brief that gets useful answers.',desc='A practical brief for a website that serves your audience, your team, and your next stage of growth.',related='websites',intro='You do not need a finished sitemap or a folder of perfect references to start a website project. You need a clear account of what the business needs, who the site is for, and what is getting in the way today.',sections=[
 ('Describe the moment that brought you here.','Start with the reason for the project. Perhaps your services have changed, visitors keep asking the same questions, or your team cannot update the existing site. Describe the problem in everyday language. “We need a modern website” tells a designer very little. “Buyers cannot tell which of our three services fits their situation” gives the project a useful direction.\n\nInclude what already works. A redesign should preserve valuable content, recognizable brand elements, and routes that customers rely on. A short list of strengths is as useful as a list of frustrations.'),
 ('Name the audience and the next action.','Choose a primary visitor and explain what they know before arriving. A first-time customer needs different context from an existing client searching for support. List the questions that visitor must answer before taking the next step.\n\nThen choose the action that matters: send an enquiry, book a conversation, compare a service, or complete a purchase. Several actions can exist, but treating them all as equally important makes the page harder to design. For each main page, write one sentence that completes “After reading this, the visitor should be able to…”'),
 ('Make content somebody’s responsibility.','List the material you have: copy, photography, brand files, product details, testimonials with permission, and translations. Mark what is ready and what still needs work. Content delays often become design delays because the layout is being asked to solve an unanswered messaging question.\n\nAssign a person to approve factual claims and a person to collect feedback. If five colleagues need to review, agree how their comments become one decision. This keeps the project from circling between contradictory edits.'),
 ('Share constraints before references.','Explain your deadline and what makes it important. A trade show, a campaign, or the end of an existing contract creates different priorities. Give a budget range if you have one, and identify systems the site must connect to.\n\nReferences help most when they come with reasons. Instead of “make it like this,” explain that you like the navigation clarity, photography scale, or restraint of the animation. Separate visual preferences from functional requirements so neither is mistaken for the other.'),
 ('Finish with a one-page starting brief.','Use these prompts: What changed in the business? Who is the main visitor? What should they understand or do? Which pages and assets already exist? What systems must remain? Who approves content? What is the budget range and target date?\n\nUnknown answers are welcome. Label them as decisions to make together. The purpose of a brief is to make the first conversation more useful, not to do the entire design process before speaking to a designer.')]),
 dict(slug='first-version-of-your-app',category='Digital',title='Your first app does not need every feature.',desc='How to define a first release around one complete journey instead of an impressive feature list.',related='apps',intro='A smaller first release can still feel complete. The key is to reduce the number of jobs the product does while keeping the chosen journey understandable from beginning to end.',sections=[
 ('Choose one real working day.','Describe one person using the product on an ordinary day. What triggers the visit? What information do they bring? What result do they need before leaving? This is more useful than beginning with a menu of dashboards, settings, notifications, and integrations.\n\nFor a simple client portal, the initial journey might be: open a project, review the latest deliverable, leave a comment, and see that the comment was received. Advanced reporting can wait if it does not help that journey succeed.'),
 ('Draw the whole journey, including the boring parts.','A product is more than the screen shown in the pitch deck. Someone arrives without data, makes a mistake, loses a connection, or does not have permission to continue. Put those moments into the plan early.\n\nThe first version needs a clear empty state, useful validation, a visible saved state, and a way to recover from common mistakes. These details may create more trust than a second dashboard. Write down who owns each record and who can change it before designing the controls.'),
 ('Separate essential from attractive.','For each proposed feature, ask whether the primary journey can work without it. If yes, it belongs in a later discussion unless it addresses a critical risk. This does not mean the feature is a bad idea. It means the team is choosing an order.\n\nKeep a parking list with the reason each feature was deferred. When real users ask for something similar, revisit the original assumption. A dated list of decisions is more useful than a growing backlog with no explanation of priorities.'),
 ('Test a prototype with a task.','Show a person a realistic scenario and ask them to complete it. Avoid explaining every control before they start; that turns the test into a demonstration. Watch where they hesitate, what they misunderstand, and which information they look for first.\n\nA prototype can expose language and navigation problems before the underlying system exists. It cannot prove performance, security, or reliability. Use it to answer questions about the experience, then validate the implemented product against the technical risks separately.'),
 ('Define a release you can learn from.','Decide what evidence would make the first release useful. Can users complete the main task? Which steps require help? Which mistakes recur? Choose a small set of questions that can guide the next iteration.\n\nAgree on support, access management, backups, and ownership before launch. A first release is a beginning, but it still needs someone responsible for it. A focused product with a clear owner is easier to improve than a broad product that nobody can confidently operate.')]),
 dict(slug='automation-needs-an-owner',category='Intelligence',title='An automation is only as good as its recovery plan.',desc='Duplicate events, failed connections, and changed data: plan for the moments when a workflow needs help.',related='automations',intro='The demo usually follows the ideal path. Everyday work includes missing fields, expired access, duplicate requests, and tools that become unavailable. A useful automation makes these situations visible and recoverable.',sections=[
 ('Write down what must happen exactly once.','Consider a workflow that creates a project when an enquiry is approved. Receiving the approval twice should not create two projects. Decide how the workflow recognizes that the business action has already happened.\n\nThe answer might be a stable enquiry identifier attached to the resulting record. The important point is that identity belongs to the business event, not merely to a particular execution attempt. Review this rule for invoices, customer messages, and other steps where repetition could cause confusion.'),
 ('Separate temporary failures from bad input.','A connection timeout and a missing customer address need different responses. Retrying a temporary connection problem may help. Retrying a record that lacks required information simply repeats the failure.\n\nDescribe the expected errors in plain language and give each a next step. Some can wait and retry within a limit. Others should stop, explain what is missing, and ask an owner to correct the record. Never let endless retries substitute for a decision about the failure.'),
 ('Make the status useful to a person.','A technical error message may help a developer but leave an operations team with no idea whether a customer was contacted. Show the stage that completed, the stage that did not, and whether the action can be safely retried.\n\nKeep logs proportionate. A useful audit trail records what happened without copying unnecessary personal data or secrets into every message. Decide who can inspect the history and how long it needs to exist for the actual operational purpose.'),
 ('Put approval where judgment matters.','A workflow can gather information and prepare a proposed action while leaving the final decision to a person. Approval is particularly useful when the input is ambiguous or the result affects a customer relationship.\n\nGive the reviewer enough context to judge the action. “Approve?” is not a complete review interface. Show the proposed result, the source information, and what will happen after approval. Also define what happens if nobody responds: wait, escalate, or expire the request.'),
 ('Hand over more than a diagram.','Document the owner, connected accounts, normal schedule, expected output, and recovery steps. Include a safe way to pause the workflow. The documentation should answer what to check when the expected result does not appear.\n\nBefore launch, deliberately test one duplicate event, one missing field, and one disconnected dependency. Watch the recovery path as carefully as the successful run. These small rehearsals reveal whether the workflow is ready to become part of someone’s working day.')]),
 dict(slug='brand-handover-that-works',category='Design',title='What belongs in a brand handover?',desc='The files, examples, and everyday rules that help a visual identity stay consistent after launch.',related='branding',intro='An identity is not finished when the presentation looks beautiful. It is ready when the people using it can make the next proposal, social post, or printed item without guessing how the brand works.',sections=[
 ('Build the handover around everyday tasks.','Ask what the team creates most often. A sales proposal, an email signature, a social campaign, and a product label each need different formats. Prioritize the tools that will be used next week rather than filling a folder with every possible variation.\n\nGive each template a clear owner and a short explanation of what may change. A template becomes less useful when people cannot tell whether the headline size, image crop, or color is fixed or simply an example.'),
 ('Make logo files understandable.','Organize logo variations by purpose: full identity, compact mark, light background, dark background, and single color. Include appropriate vector and raster formats within the agreed scope. Use filenames a colleague can understand without opening every file.\n\nShow minimum-size and spacing examples in actual contexts. A rule explained through a small mobile header or a narrow label is easier to apply than an abstract diagram alone. Check the mark at the sizes where people will really encounter it.'),
 ('Explain typography as a hierarchy.','A list of font names does not explain how to write a page. Show a headline, a subheading, body text, a caption, and a call to action together. Include examples with realistic lengths so the rules survive ordinary content.\n\nClarify font licensing and where the files come from. If a typeface is not available in a common office tool, define a suitable fallback and demonstrate it. This avoids a team improvising a different substitute in every document.'),
 ('Give imagery a point of view.','Describe subjects, framing, lighting, color, and the relationship between images and text. Examples of what to avoid are useful when they explain the reason rather than simply marking a picture as wrong.\n\nFor generated or edited imagery, keep a consistent reference set and document the review process. Check factual details, unwanted text, and brand elements before release. A production method does not remove the need for art direction or permission to use source material.'),
 ('Test the kit without the designer in the room.','Ask a colleague to create one realistic item using only the handover. Notice where they hesitate or invent a rule. Those moments reveal what the documentation needs to explain.\n\nFinish with a contents page, a version date, and a place for the approved files. An identity will evolve, so separate current assets from old drafts. The best brand handover makes consistent work easier to produce, review, and maintain.')]),
 dict(slug='designing-forms-people-finish',category='Digital',title='A better enquiry form starts with fewer questions.',desc='Design a first-contact flow that respects attention and gives you enough context for a useful reply.',related='websites',intro='A visitor may be ready to talk without being ready to specify an entire project. A good enquiry flow asks for what is needed now and leaves room for the conversation to develop.',sections=[
 ('Decide what the first reply needs.','Work backwards from the person responding. Which information helps them send a relevant answer? A name, a reply address, and a short description may be enough for the first exchange. A detailed procurement process might need more, but every extra field should have a purpose.\n\nIf a field is useful only much later, move it to that stage. Asking for a full address, a fixed budget, or a precise launch date too early can exclude people who have a good project but have not resolved every detail.'),
 ('Make uncertainty an acceptable answer.','Provide “not sure yet” where uncertainty is normal. Budget and timing questions can use ranges or a free-text explanation rather than forcing a false level of precision.\n\nThe language of the form should sound like the conversation you want to have. Explain why a question matters when that is not obvious. A brief note such as “This helps us suggest a realistic starting point” can give a visitor confidence that the information has a purpose.'),
 ('Keep labels visible and errors specific.','A label should remain available while a person types. Placeholder text alone disappears at the moment someone may need to remember the question. Mark optional and required fields clearly, and keep instructions near the relevant control.\n\nAn error should identify the problem and the next step. “Something went wrong” is less helpful than explaining that a reply address is missing. Preserve what the visitor has already entered so correcting one field does not become a complete restart.'),
 ('Explain what happens when they continue.','A button should make the next action clear. Opening an email draft, submitting to a server, and booking a meeting are different outcomes. Do not make an email handoff look like a completed submission.\n\nAfter a successful submission, confirm what was received and what happens next. Only promise a response time the business can actually support. For an email draft, remind the visitor that they still need to review and send the message in their email application.'),
 ('Review the flow on a real small screen.','Check input types, keyboard behavior, long names, error messages, and focus order. A form that looks compact in a desktop design may become awkward when the keyboard covers half the phone.\n\nMake the privacy information easy to find at the point of contact. Ask people to share a useful project outline without including passwords, payment details, or sensitive records. A first enquiry should begin a conversation, not require someone to transfer their whole business into a text box.')]),
 dict(slug='ai-film-continuity',category='Film',title='Continuity makes an AI-assisted film feel like a film.',desc='A practical reference system for characters, locations, props, camera direction, and the edit.',related='film-video',intro='A convincing shot can still fail inside a sequence. The audience follows a character through space and time, so each frame needs to belong to the same world and support the next moment.',sections=[
 ('Create a small continuity bible.','Collect approved references for each character, costume, prop, and location. Record the details that must remain stable: a ring, a jacket fastening, the position of a doorway, or the shape of a key. Keep those references separate from exploratory images.\n\nWrite down the scene’s physical rules. Where does the light come from? Which direction does a character enter? What is held in each hand? A short, precise record gives the team something to check when a frame looks attractive but does not match the scene.'),
 ('Choose frames for their place in the edit.','Plan a shot around its beginning, its action, and its ending. An end frame is not just a composition; it is a handoff to the next shot. Consider eye direction, body position, and whether the audience understands where the character is looking.\n\nBuild a rough sequence early, even if it uses still images. A sequence often reveals missing information that is invisible when reviewing individual frames. You may need a simple establishing shot more than another dramatic close-up.'),
 ('Keep camera language intentional.','Distance, angle, and movement should help express the scene. If every shot is an orbit, a push-in, or an extreme close-up, the camera can distract from what changes between the characters.\n\nUse movement selectively. A static shot can give a gesture time to land. A wider view can restore geography after several close shots. The purpose is not to limit visual ambition, but to make the audience feel that the camera is paying attention to the story.'),
 ('Review motion and contact, not just faces.','Look carefully at hands touching props, feet meeting the floor, fabric moving with the body, and objects crossing in front of one another. These interactions often carry the credibility of the shot.\n\nWatch at normal speed before inspecting still frames. Then inspect the moments where contact or direction changes. A small artifact that interrupts the action may matter more than an imperfect background detail that nobody notices during the edit.'),
 ('Use sound to test the rhythm.','Add rough dialogue, footsteps, atmosphere, or silence early. Sound can reveal that a shot needs more time, that a cut feels abrupt, or that an action is difficult to understand.\n\nReview the final sequence with the original story intention beside it. What changes emotionally? What does the audience learn? Keep the shots that serve those answers. A coherent short film is more memorable than a collection of unrelated impressive images.')]),
 dict(slug='designing-with-motion',category='Design',title='When motion helps a website—and when it gets in the way.',desc='Give animation a purpose, keep the reading experience intact, and design a quieter alternative.',related='3d-experiences',intro='Motion can explain a relationship, reveal a product, or give a brand a distinctive presence. It works best when the visitor can still read, navigate, and choose their own pace.',sections=[
 ('Give each movement a job.','Ask what the animation communicates. A transition can connect two states. A product rotation can reveal a feature. A scroll sequence can make a story unfold in a particular order. If the movement exists only because it was easy to add, it may not earn the attention it takes.\n\nChoose one dominant moment on a page and let supporting elements remain calmer. When every heading, card, and background moves independently, the visitor has to work harder to decide what matters.'),
 ('Protect the reading area.','Text needs a stable place to be read. Avoid moving long paragraphs continuously or placing bright visual changes directly behind the main copy. Give important information enough time and contrast to remain understandable.\n\nFor scroll-driven sequences, write the story in beats. Each beat should work as a clear thought, and the transitions should follow the visitor’s progress. If someone scrolls quickly, they should still be able to understand the page and reach the next section.'),
 ('Design the phone composition separately.','A desktop scene with wide side columns may not fit a narrow portrait screen. Decide which element carries the meaning, then allocate space around it. Supporting work can become smaller, stack below, or move into a simpler sequence.\n\nAccount for browser controls and short landscape viewports. A pinned composition that depends on a tall screen can trap content below the fold. In that situation, an ordinary scrolling layout may tell the story better.'),
 ('Offer a complete quieter experience.','Reduced motion should preserve the information, links, and actions. It can replace a long pinned sequence with a still image and readable sections. Do not hide the core story merely because animation has been turned off.\n\nA visible motion control also gives people a choice for the current visit. Consider keyboard focus: an animated item should not move away from a person trying to open it. Pause or simplify the presentation when interaction requires stability.'),
 ('Treat performance as part of the design.','Load large decorative media near the point where it will be used. Use an appropriate poster while a video is not ready, and avoid making the entire page depend on a visual effect completing successfully.\n\nReview on ordinary devices and connections as well as powerful desktops. If the effect makes the interface feel delayed, simplify it. The strongest animation feels integrated into the experience, with useful content still available when the visual layer cannot run.')]),
 dict(slug='prepare-your-content-for-ai',category='Intelligence',title='Before an AI assistant, put your knowledge in order.',desc='A practical content review for teams planning an assistant that answers from internal information.',related='ai-solutions',intro='An assistant cannot resolve a company’s conflicting policies by sounding confident. Before connecting your documents, decide which information is current, who owns it, and who should be allowed to see it.',sections=[
 ('Start with a small trusted collection.','Choose the documents needed for one specific task. A focused support assistant might start with approved product guidance and a set of common questions. Connecting every shared folder at once makes it harder to understand where an answer came from.\n\nGive each source an owner and a review date. Where two documents disagree, ask a person to resolve the conflict. Do not leave the assistant to choose which version is authoritative based on wording or file location.'),
 ('Write for retrieval as well as reading.','Use descriptive headings and keep related information together. Define abbreviations and identify the product, policy, or process a section concerns. A paragraph copied out of a document should still contain enough context to be understood.\n\nSeparate instructions from examples. Make dates and exceptions explicit. If a policy applies only to one region or one customer group, include that condition near the rule rather than only in a cover page that may be separated during processing.'),
 ('Map access before connecting systems.','Different people may have permission to read different sources. An assistant should not expose information simply because its integration account can see it. Design around the requesting user’s access and the sensitivity of the material.\n\nUse representative but appropriate test data during early development. Avoid sending confidential records into a tool before the organization has reviewed the provider, settings, and intended use. The integration design should explain where information travels and who can inspect it.'),
 ('Build questions with known answers.','Collect realistic questions and have a knowledgeable person write the expected answer and supporting source. Include questions with no answer in the collection, outdated information, and ambiguous wording.\n\nReview whether the assistant cites the correct material, preserves exceptions, and admits when information is missing. A fluent answer is not enough. The evaluation should reflect the consequence of a mistake in the particular workflow.'),
 ('Make maintenance part of the launch.','Choose how changes reach the assistant and how removed documents stop being used. Assign someone to review reported errors and update the trusted collection. A knowledge system is a living part of the business.\n\nStart with a limited audience and gather feedback on actual tasks. Look for recurring missing information rather than treating every poor answer as a prompt problem. Sometimes the most useful improvement is a clearer source document that helps both people and the assistant.')])
]
