PRIVACY = '''<p class="eyebrow">PRIVACY NOTICE · UPDATED 5 OCTOBER 2026</p><h1>Your information.<br>Your choices.</h1><p class="body-large">This notice covers the Helmies website and enquiries you choose to send to Helmies Oy, Finland. Privacy questions and requests: <a href="mailto:info@helmies.fi?subject=Privacy%20request">info@helmies.fi</a>.</p>
<nav class="legal-nav" aria-label="Privacy contents"><a href="#information">Information & purposes</a><a href="#storage">Storage & providers</a><a href="#rights">Your rights</a><a href="/cookies/">Cookies & device storage</a></nav>
<h2 id="information">What happens when you visit</h2><p>The website has no Helmies advertising pixels, visitor analytics integration, or account registration. Fonts, portfolio thumbnails, and the founder video are served as website assets. Opening a portfolio link takes you to Behance; the page does not embed Behance tracking widgets.</p><p>Delivering a website requires technical requests to its host. These can contain an IP address, browser information, requested address, and request time. This site is hosted through ChatGPT Sites. Hosting or account-layer processing is separate from the website’s page features; see <a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener noreferrer">OpenAI’s privacy information</a> for its services.</p>
<h2>Project briefs and messages</h2><p>The brief builder uses the information you type in the current page to prepare an email. It does not submit the brief to a Helmies server, save it to browser storage, or send it to an AI model. Opening the draft passes its contents to your chosen email application. You decide whether to send it.</p><p>If you email us, Helmies receives your address, the name and contact details you include, your message, and any attachments. We use this information to answer the enquiry and discuss the requested work. Taking steps at your request before a contract can provide the legal basis for that processing; responding to a business representative’s enquiry can instead rely on the legitimate interest of handling business correspondence. Information required for a resulting engagement is addressed in the project’s arrangements.</p><p>Sharing information is voluntary, but we need a way to reply and enough context to understand your request. Please do not include passwords, payment-card information, or sensitive personal records in an initial brief. An early-access email is an enquiry, not an automatic newsletter subscription.</p>
<h2 id="storage">Who handles information</h2><p>Your chosen email provider handles the draft and delivery. Helmies’ email and hosting providers support receipt of communications and delivery of the site. External destinations operate their own services and privacy practices. We do not publish your enquiry on this website or use this website to sell personal data.</p><p>Provider locations, contractual safeguards, and retention arrangements can differ between services. This notice does not make an EU-only hosting promise. Contact us before sending material that needs a specific processing location or a data-processing agreement, so the relevant providers and any international-transfer safeguards can be confirmed for the proposed work.</p>
<h2>How long information is kept</h2><p>A brief exists in the current page until you leave or reset it; your browser may restore a page during a browsing session. A copied brief remains in your device clipboard until replaced or cleared. Once an email is sent, it becomes correspondence rather than temporary website input.</p><p>The appropriate retention of correspondence depends on whether an enquiry remains active, becomes a project, or must be retained for a legal obligation or a claim. Ask us about the retention or deletion of a specific message. This page does not promise an automatic mailbox deletion schedule that the website cannot enforce.</p><p>Device-storage lifetimes and deletion controls are listed on the <a href="/cookies/">cookies and device storage page</a>.</p>
<h2 id="rights">Your GDPR rights</h2><p>Depending on the circumstances, you can request access, correction, erasure, restriction, or portability of personal data, and object to processing based on legitimate interests. Where processing relies on consent, you can withdraw it without affecting earlier lawful processing. These rights have conditions and exceptions.</p><p>Email <a href="mailto:info@helmies.fi?subject=Personal%20data%20request">info@helmies.fi</a> with your request. Include enough information to locate the relevant correspondence; avoid sending identity documents unless needed and requested. GDPR requests generally require a response within one month, with a possible extension for complex or numerous requests.</p><p>You may lodge a complaint with Finland’s <a href="https://tietosuoja.fi/en/notification-to-the-data-protection-ombudsman" target="_blank" rel="noopener noreferrer">Data Protection Ombudsman</a> or another competent supervisory authority. Read the <a href="https://commission.europa.eu/law/law-topic/data-protection/information-individuals_en" target="_blank" rel="noopener noreferrer">European Commission’s explanation of individual rights</a>.</p>
<h2>Automated decisions and AI</h2><p>The website does not make decisions with legal or similarly significant effects about visitors. The service navigator matches choices to service suggestions in your browser. Search checks the site’s own content index. Neither feature sends your input to a generative AI service.</p>
<h2>Changes and project-specific information</h2><p>This notice describes this website. A future product, client project, newsletter, or new integration may require additional information and choices before it is used. The date above identifies this revision.</p>'''
COOKIES = '''<p class="eyebrow">COOKIES & DEVICE STORAGE · UPDATED 5 OCTOBER 2026</p><h1>A clear view<br>of what stays.</h1><p class="body-large">Helmies’ website code sets no advertising or analytics cookies. It uses a few browser preferences and offers optional offline storage. You can read the site without enabling offline storage.</p>
<div class="privacy-controls"><h2>Offline pages</h2><p>If enabled, a service worker saves public pages and assets on this device for repeat visits without a connection. It does not save your brief, and it does not cache the founder video. Turning it off removes the Helmies offline cache.</p><div class="control-actions"><button class="button ghost" data-offline="on">Enable offline pages</button><button class="button ghost" data-offline="off">Disable & clear offline pages</button></div><p id="offline-status" role="status" aria-live="polite"></p></div>
<h2>Storage used by the website</h2><div class="storage-table"><table><thead><tr><th>Item</th><th>Purpose</th><th>Duration</th></tr></thead><tbody><tr><td>helmies-motion<br><small>Local storage</small></td><td>Remembers the motion setting you choose.</td><td>Until cleared or changed; no automatic expiry.</td></tr><tr><td>helmies-announcement-v2<br><small>Session storage</small></td><td>Remembers that you dismissed the announcement.</td><td>The browser tab’s session, subject to browser session restoration.</td></tr><tr><td>helmies-offline<br><small>Local storage</small></td><td>Records your explicit offline-storage choice.</td><td>Until you change it or clear site data.</td></tr><tr><td>helmies-*<br><small>Cache Storage</small></td><td>Public pages and assets, only with offline pages enabled.</td><td>Until disabled, replaced by an update, cleared, or removed by your browser.</td></tr></tbody></table></div>
<h2>Device tilt and motion</h2><p>Device tilt is off until you enable it. Where required, the browser asks for sensor permission. Orientation readings move decorative visuals in the page; the website does not send them to Helmies. Use the footer controls to turn tilt or motion off. The site also respects your device’s reduced-motion preference.</p>
<h2>Hosting and external services</h2><p>This inventory covers storage created by Helmies’ website code. Browser caching and the ChatGPT Sites hosting or account layer may operate separately. External services, including your email app and Behance after you follow a link, have their own settings and policies. Read our <a href="/privacy/">privacy notice</a> for more context.</p>
<h2>Reset your website preferences</h2><p>This removes the Helmies motion and announcement preferences, disables offline storage, and clears its saved public pages on this device. It does not delete sent emails, clipboard content, or data held by external providers.</p><button class="button ghost" id="reset-site-preferences">Reset Helmies preferences</button><p id="reset-status" role="status" aria-live="polite"></p><p>You can also remove site data through your browser settings. Clearing browser data does not send a deletion request to Helmies.</p>
<h2>About consent</h2><p>Optional storage should follow a clear, freely made choice that can be withdrawn. Our offline controls let you enable or disable this feature without blocking access to the site. See <a href="https://www.traficom.fi/sites/default/files/media/file/Guidance_on_the_use_of_web_cookies_for_the_service_providers.pdf" target="_blank" rel="noopener noreferrer">Traficom’s guidance on cookies and similar technologies</a>.</p>'''
FAQS = [
 ('What should I send in a first enquiry?','A short description of the idea, who it is for, what needs to change, and any important deadline. Existing links and references are useful. You do not need a polished brief; unknowns can be discussed together.'),
 ('Can a project combine several services?','Yes. An identity, website, campaign, and connected workflow can be scoped as one coordinated project. We agree which parts are needed now and which can follow later.'),
 ('How do we decide on the budget?','We look at deliverables, complexity, content needs, integrations, and review stages before preparing a proposal. Share a range if you have one so the approach can fit the investment.'),
 ('Can you give a fixed launch date?','A target date is agreed after checking scope, availability, content readiness, and outside dependencies. Let us know what makes the date important so we can plan priorities realistically.'),
 ('Do I work directly with Wael?','Helmies is a founder-led studio. Wael connects the design and technical direction. Any additional collaborators and their responsibilities are discussed as part of the project scope.'),
 ('Can you work with our existing brand or developers?','Yes. Share current guidelines, source files, and relevant constraints. We can take responsibility for a defined part of the work and agree how reviews and handoffs fit your team.'),
 ('Who supplies the website content?','We agree this in the scope. You provide business facts and approve claims; writing, editing, photography, or asset production can be included where needed. One content owner helps keep decisions clear.'),
 ('How many rounds of revisions are included?','Review stages and revision allowances belong in the proposal. Feedback is most useful when consolidated into one response tied to the agreed goals. New directions or added deliverables may change the scope.'),
 ('What do I receive at handover?','The agreed production files, access, and usage guidance for your project. Source files, third-party licenses, account ownership, and usage rights should be specified before work begins.'),
 ('Do you provide ongoing support?','Maintenance, content updates, monitoring, and further development can be scoped separately. We clarify ongoing ownership and any support arrangement before delivery.'),
 ('Can an AI project use confidential material?','That needs a specific review of access, providers, data locations, permissions, and retention before information is connected. Start with a description of the task rather than sending sensitive records in the first email.'),
 ('Will sending a brief subscribe me to marketing?','No. The website prepares an email for you to review and send. It does not subscribe you to a mailing list or automatically submit your details.'),
]
